### ISSUE TITLE
제이마나 다운 안되는거 정보 추가한 했어요 ㅠ

### ISSUE THREAD

**Issue by 1818181881** [KurtBestor/Hitomi-Downloader-issues#1609] opened 2020-01-25 14:33 UTC
제이마나 맛의 달인, 이니셜D

Invalid: [jmana] https://jmana2.net / book / %EC%9D%B4%EB%8B%88%EC%85%9C%20D

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://jmana2.net/book/%EC%9D%B4%EB%8B%88%EC%85%9C%20D
dir: 
zip: 
type: jmana
artist: None
url: https://jmana2.net/book/%EC%9D%B4%EB%8B%88%EC%85%9C%20D
valid: False
done: True
range: None
range_p: None
single: False
time: 1579962728.91 (Jan 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
No title
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "jmana_downloader", line 85, in read
File "jmana_downloader", line 78, in name
File "jmana_downloader", line 108, in get_title
Exception: No title

Invalid: fail=True
EOT: https://jmana2.net/book/%EC%9D%B4%EB%8B%88%EC%85%9C%20D

Invalid: [jmana] https://jmana2.net / book / %EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8

version: 2.7h
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8
dir: 
zip: 
type: jmana
artist: None
url: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8
valid: False
done: True
range: None
range_p: None
single: False
time: 1579962715.88 (Jan 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
No title
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "jmana_downloader", line 85, in read
File "jmana_downloader", line 78, in name
File "jmana_downloader", line 108, in get_title
Exception: No title

Invalid: fail=True
EOT: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8
![캡처](https://user-images.githubusercontent.com/60257088/73122693-2206bf80-3fcb-11ea-9a70-42a37e2b356e.PNG)

테스트 버전으로 다운해서 해봤는데도 같아요 ㅠ
Invalid: [jmana] https://jmana2.net / book / %EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8
dir: 
zip: 
type: jmana
artist: None
url: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8
valid: False
done: True
range: None
range_p: None
single: False
time: 1579964574.54 (Jan 26)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
No title
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "jmana_downloader", line 85, in read
File "jmana_downloader", line 78, in name
File "jmana_downloader", line 108, in get_title
Exception: No title

Invalid: fail=True
EOT: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8

![캡처](https://user-images.githubusercontent.com/60257088/73123082-259c4580-3fcf-11ea-8672-8a21ae7cc19a.PNG)

**Comment by KurtBestor** [comment] 2020-01-28 10:07
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1602

**Closed** 2020-01-28 10:08 UTC
